language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mjrode/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mjrode/docker-react npm run test
